server:
  port: 8080
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy #org.mariadb.jdbc.Driver
    url: jdbc:log4jdbc:mariadb://localhost:3306/mybatis_db?serverTimezone=UTC&characterEncoding=UTF-8 # jdbc:mariadb://localhost:3306/mybatis_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org.springframework.jdbc.core: debug
    com.mybatis.crud.demo: info
mybatis:
  type-aliases-package: com.mybatis.crud.demo.entity
#  mapper-locations: /com/mybatis/crud/demo/mapper/**/*.xml